name: Actualizar Tarjetas del README
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Concede permiso de escritura a nivel de tarea obligatoria
    steps:
      - uses: actions/checkout@v4
      
      - name: Generar tarjeta de estadísticas
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=dagdmfc1946&show_icons=true&theme=radical&include_all_commits=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generar tarjeta de lenguajes
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=dagdmfc1946&layout=compact&theme=radical&langs_count=6
          path: profile/langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Reemplazamos el comando manual por una acción dedicada que maneja el error 128
      - name: Guardar tarjetas de forma segura
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README cards"
          file_pattern: 'profile/*.svg'
